### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by syngrato** [otovo/python-brreg#3]
What would be involved in lowering the Python version requirement to 3.5? Happy to submit a patch if you could possibly provide some guidance.

**Comment by syngrato** [comment]
I have figured out what code needs updating to make brreg 3.5 compatible. Would you be interested in a patch?

**Comment by klette** [comment]
@syngrato Please submit a PR and we'll have a look :-)

Thanks!

**Comment by maacl** [comment]
Any news regarding this?

**Comment by jodal** [comment]
I no longer work at Otovo, so I don't answer for them.

With only seven months left until Python 3.5 reaches end of life I don't think anyone at Otovo has any interest in backporting this library to 3.5. I believe that your only way to make that happen is to provide a PR doing the work.

If it was up up me, I'd instead consider increasing the minimum version to 3.7 and replace the use of the attrs library with dataclasses from the Python standard library.

**Comment by maacl** [comment]
Thanks for replying anyway. I already submitted a PR, but I see your point re end-of-life of 3.5.

**Comment by sondrelg** [comment]
Added a comment in the PR. Closing under the assumption that this is no longer needed :+1:
